#!/bin/bash

## usage: mvln myfile.file mydir/

## I am not sure whether this works with a complicated example of mydir/
## I have only tested it by being in the same dir as myfile.file and choosing a mydir that is a sub-dir of the current dir.

mv $1 $2 
ln -rs $2/$1 $1
